spring:
  datasource:
    url: jdbc:mysql://localhost:3307/dog
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: springuser
    password: springuser
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
